### PR TITLE
Update Player.cs

### PR DESCRIPTION
**Pull request by dretax**
Added Metabolism options.

Some of these might need setters. Please check those out.

Note: I probably screwed this pull, so if you want you can check what i added, and add them manually.

### CODE REVIEW

**Comment by mikecrews** [comment]
Yes, the pull is messed up because the tabs are using a different setting than the project is using.  This makes every line a change, so I will add the new methods myself. Thanks.

**Comment by dretax** [comment]
Sorry. :D

**Comment by dretax** [comment]
Could you please also put this function in?

public void Damage(float dmg)
{
         TakeDamage.HurtSelf(this.PlayerClient.controllable.character, dmg);
}

**Comment by mikecrews** [comment]
9270999f28b8d00fb52337c4fd70376c0cb8f9b0 Adding poison will make the player vomit. :)

I need to add the Damage method still.

**Pull request closed without merging**
